#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build-chongshengB-Padavan

on: 
  workflow_dispatch:
  release:
    types: [published] 
  watch:
    types: [started]
    
env:
  TNAME: NEWIFI3
  build_dir: /opt/rt-n56u                                       # 源码目录
  images_dir: /opt/images                                       # 固件目录
  work_dir: /opt/rt-n56u/trunk                                  # 工作目录 
  src_git: https://github.com/chongshengB/rt-n56u.git           # 源码地址
  config_dir: /opt/rt-n56u/trunk/configs/templates              # 设备模板目录
  toolchain_dir: /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x  # 工具链目录
  toolchain_pkg: mipsel-linux-uclibc.tar.xz
  toolchain_url: https://github.com/TurBoTse/padavan-toolchain/releases/download/v1.0
   
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        # cd $build_dir/toolchain-mipsel
        # sh dl_toolchain.sh
        mkdir -p $toolchain_dir && mkdir -p $images_dir
        curl -LO ${toolchain_url}/${toolchain_pkg}
        tar -xf $toolchain_pkg -C $toolchain_dir
    - name: Build Firmware
      run: |
        cd $work_dir
        sudo ./clear_tree
        fakeroot ./build_firmware_ci $TNAME
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
